################################################################################
# Makefile for building and running docker containers
#
# OPERATIONAL version
operational_build:
	docker build -t monitoring-node-utils:v1.0.0 -t monitoring-node-utils:latest -f Dockerfile .

